/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/prisoners/{offenderNo}/visits/{visitId}/cancel': {
    put: operations['cancelVisit']
  }
  '/prisoners/{offenderNo}/visits': {
    /** Creates a new visit and decrements the visit balance. */
    post: operations['createVisit']
  }
  '/visits/{visitId}': {
    /** Retrieves a visit by id. */
    get: operations['getVisit']
  }
  '/visits/rooms/usage-count': {
    /** Retrieves a list of rooms with usage count for the (filtered) visits */
    get: operations['getVisitRoomCountsByFilter']
  }
  '/visits/ids': {
    /** Retrieves a paged list of visits by filter */
    get: operations['getVisitsByFilter']
  }
}

export interface components {
  schemas: {
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Visit cancellation */
    CancelVisitRequest: {
      /**
       * @description The cancellation reason
       * @enum {string}
       */
      outcome: 'VISCANC' | 'OFFCANC' | 'ADMIN' | 'NSHOW'
    }
    /** @description Visit creation request */
    CreateVisitRequest: {
      /**
       * @description Visit start date and time
       * @example 2021-07-05T10:35:17
       */
      startDateTime: string
      /**
       * @description Visit end time
       * @example 14:30
       */
      endTime: string
      /** @description Prison where the visit is to occur */
      prisonId: string
      /** @description Visitors */
      visitorPersonIds: number[]
      /** @description Whether visit is a privileged one */
      privileged: boolean
      /**
       * @description Visit type, whether social or official
       * @enum {string}
       */
      visitType: 'SCON' | 'OFFI'
      /**
       * Format: date
       * @description Issue date
       */
      issueDate: string
    }
    /** @description Visit creation response */
    CreateVisitResponse: {
      /**
       * Format: int64
       * @description The created Nomis visit id
       */
      visitId: number
    }
    /** @description NOMIS room */
    CodeDescription: {
      code: string
      description: string
    }
    /** @description Visit information */
    VisitResponse: {
      /**
       * Format: int64
       * @description The visit id
       */
      visitId: number
      /** @description The offender number, aka nomsId, prisonerId */
      offenderNo: string
      /**
       * @description Visit start date and time
       * @example 2021-07-05T10:35:17
       */
      startDateTime: string
      /**
       * @description Visit end date and time
       * @example 2021-07-05T10:35:17
       */
      endDateTime: string
      /** @description Prison where the visit is to occur */
      prisonId: string
      /** @description Visitors */
      visitors: components['schemas']['Visitor'][]
      visitType: components['schemas']['CodeDescription']
      visitStatus: components['schemas']['CodeDescription']
      agencyInternalLocation?: components['schemas']['CodeDescription']
      /** @description Visit comments */
      commentText?: string
      /** @description Visitor concerns text */
      visitorConcernText?: string
    }
    /** @description Visitors */
    Visitor: {
      /**
       * Format: int64
       * @description visitor NOMIS person Id
       */
      personId: number
      /** @description Indicates lead visitor for the visit */
      leadVisitor: boolean
    }
    Pageable: {
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      sort?: string[]
    }
    /** @description Visit id */
    VisitRoomCountResponse: {
      /** @description The internal location description */
      agencyInternalLocationDescription: string
      /** Format: int64 */
      count: number
    }
    PageVisitIdResponse: {
      /** Format: int32 */
      totalPages?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      size?: number
      content?: components['schemas']['VisitIdResponse'][]
      /** Format: int32 */
      number?: number
      sort?: components['schemas']['Sort']
      last?: boolean
      first?: boolean
      /** Format: int32 */
      numberOfElements?: number
      pageable?: components['schemas']['PageableObject']
      empty?: boolean
    }
    PageableObject: {
      /** Format: int64 */
      offset?: number
      sort?: components['schemas']['Sort']
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      pageNumber?: number
      paged?: boolean
      unpaged?: boolean
    }
    Sort: {
      empty?: boolean
      sorted?: boolean
      unsorted?: boolean
    }
    /** @description Visit id */
    VisitIdResponse: {
      /**
       * Format: int64
       * @description The visit id
       */
      visitId: number
    }
  }
}

export interface operations {
  cancelVisit: {
    parameters: {
      path: {
        offenderNo: string
        visitId: number
      }
    }
    responses: {
      /** Visit cancelled */
      200: unknown
      /** Invalid cancellation reason */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** VSIP visit id not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelVisitRequest']
      }
    }
  }
  /** Creates a new visit and decrements the visit balance. */
  createVisit: {
    parameters: {
      path: {
        offenderNo: string
      }
    }
    responses: {
      /** Visit information with created id */
      201: {
        content: {
          'application/json': components['schemas']['CreateVisitResponse']
        }
      }
      /** Prison or person ids do not exist */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** offenderNo does not exist */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateVisitRequest']
      }
    }
  }
  /** Retrieves a visit by id. */
  getVisit: {
    parameters: {
      path: {
        visitId: number
      }
    }
    responses: {
      /** Visit Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['VisitResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** visit does not exist */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a list of rooms with usage count for the (filtered) visits */
  getVisitRoomCountsByFilter: {
    parameters: {
      query: {
        pageRequest: components['schemas']['Pageable']
        /** Filter results by prison ids (returns all prisons if not specified) */
        prisonIds?: string[]
        /** Filter results by visitType (returns all types if not specified) */
        visitTypes?: string[]
        /** Filter results by visits that start on or after the given timestamp */
        fromDateTime?: string
        /** Filter results by visits that start on or before the given timestamp */
        toDateTime?: string
      }
    }
    responses: {
      /** list of visit room and count is returned */
      200: {
        content: {
          'application/json': components['schemas']['VisitRoomCountResponse'][]
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a paged list of visits by filter */
  getVisitsByFilter: {
    parameters: {
      query: {
        pageRequest: components['schemas']['Pageable']
        /** Filter results by prison ids (returns all prisons if not specified) */
        prisonIds?: string[]
        /** Filter results by visitType (returns all types if not specified) */
        visitTypes?: string[]
        /** Filter results by visits that start on or after the given timestamp */
        fromDateTime?: string
        /** Filter results by visits that start on or before the given timestamp */
        toDateTime?: string
        /** if true exclude visits without an associated room (visits created during the VSIP synchronisation process) */
        ignoreMissingRoom?: boolean
      }
    }
    responses: {
      /** Pageable list of visit ids is returned */
      200: {
        content: {
          'application/json': components['schemas']['PageVisitIdResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
