version: '3.1'
services:

  wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock-dash
    restart: always
    ports:
      - "9091:8080"

networks:
  hmpps_int:
