/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/prison/{prisonId}/room-mappings': {
    /** Retrieves  room mappings associated with a NOMIS prison id. Requires role NOMIS_VISITS */
    get: operations['getRoomMappings']
    /** Creates a new room mapping. Requires role NOMIS_VISITS */
    post: operations['createRoomMapping']
  }
  '/mapping/visits': {
    /** Creates a new visit and decrements the visit balance. Requires role NOMIS_VISITS */
    post: operations['createMapping']
    /** Deletes all rows from the the visit id table. Requires role NOMIS_VISITS */
    delete: operations['deleteVisitIdMappings']
  }
  '/mapping/incentives': {
    /** Creates a mapping between nomis Incentive ids and Incentive service id. Requires ROLE_NOMIS_INCENTIVES */
    post: operations['createMapping_1']
    /** Deletes all rows from the the incentive mapping table. Requires role NOMIS_INCENTIVES */
    delete: operations['deleteIncentiveMappings']
  }
  '/prison/{prisonId}/room/nomis-room-id/{nomisRoomDescription}': {
    /** Retrieves a room mapping by NOMIS prison id and NOMIS room id. Requires role NOMIS_VISITS */
    get: operations['getRoomMapping']
  }
  '/mapping/visits/vsipId/{vsipId}': {
    /** Retrieves a mapping by VSIP id. Requires role NOMIS_VISITS */
    get: operations['getVisitMappingGivenVsipId']
  }
  '/mapping/visits/nomisId/{nomisId}': {
    /** Retrieves a mapping by NOMIS id. Requires role NOMIS_VISITS */
    get: operations['getVisitMappingGivenNomisId']
  }
  '/mapping/visits/migration-id/{migrationId}': {
    /** Retrieve all mappings of type 'MIGRATED' for the given migration id (identifies a single migration run). Results are paged. */
    get: operations['getMigratedVisitMappingsByMigrationId']
  }
  '/mapping/visits/migrated/latest': {
    /** Requires role NOMIS_VISITS */
    get: operations['getLatestMigratedVisitMapping']
  }
  '/mapping/incentives/nomis-booking-id/{bookingId}/nomis-incentive-sequence/{incentiveSequence}': {
    /** Retrieves a mapping by NOMIS id. Requires role ROLE_NOMIS_INCENTIVES */
    get: operations['getIncentiveMappingGivenNomisId']
  }
  '/mapping/incentives/migration-id/{migrationId}': {
    /** Retrieve all mappings of type 'MIGRATED' for the given migration id (identifies a single migration run). Results are paged. */
    get: operations['getMigratedVisitMappingsByMigrationId_1']
  }
  '/mapping/incentives/migrated/latest': {
    /** Requires role READ_MAPPING, UPDATE_MAPPING or ADMIN_MAPPING */
    get: operations['getLatestMigratedIncentiveMapping']
  }
  '/mapping/incentives/incentive-id/{incentiveId}': {
    /** Retrieves a mapping by Incentive id. Requires role ROLE_NOMIS_INCENTIVES */
    get: operations['getIncentiveMappingGivenIncentiveId']
    /** Deletes the incentive mapping table. Requires role NOMIS_INCENTIVES */
    delete: operations['deleteIncentiveMapping']
  }
  '/prison/{prisonId}/room-mappings/nomis-room-id/{nomisRoomDescription}': {
    /** Removes room mapping given the prison and nomis room description. Requires role NOMIS_VISITS */
    delete: operations['deleteRoomMapping']
  }
}

export interface components {
  schemas: {
    /** @description NOMIS to VSIP Visit Id mapping */
    VisitMappingDto: {
      /**
       * Format: int64
       * @description nomis visit id
       */
      nomisId: number
      /** @description VSIP visit id */
      vsipId: string
      /** @description Label (a timestamp for migrated ids) */
      label?: string
      /**
       * @description Mapping type
       * @enum {string}
       */
      mappingType: 'MIGRATED' | 'ONLINE'
      /**
       * @description Date time the mapping was created
       * @example 2021-07-05T10:35:17
       */
      whenCreated?: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description NOMIS to Incentive mapping */
    IncentiveMappingDto: {
      /**
       * Format: int64
       * @description NOMIS booking id
       */
      nomisBookingId: number
      /**
       * Format: int64
       * @description NOMIS incentive sequence
       */
      nomisIncentiveSequence: number
      /**
       * Format: int64
       * @description Incentive id
       */
      incentiveId: number
      /** @description Label (a timestamp for migrated ids) */
      label?: string
      /**
       * @description Mapping type
       * @enum {string}
       */
      mappingType: 'MIGRATED' | 'NOMIS_CREATED' | 'INCENTIVE_CREATED'
      /**
       * @description Date time the mapping was created
       * @example 2021-07-05T10:35:17
       */
      whenCreated?: string
    }
    /** @description Room mapping request */
    RoomMappingDto: {
      /** @description VSIP room id */
      vsipId: string
      /** @description nomis room description (unique within prison) */
      nomisRoomDescription: string
      /** @description prison id */
      prisonId: string
      /** @description open or closed indicator */
      isOpen: boolean
    }
    Pageable: {
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      sort?: string[]
    }
  }
}

export interface operations {
  /** Retrieves  room mappings associated with a NOMIS prison id. Requires role NOMIS_VISITS */
  getRoomMappings: {
    parameters: {
      path: {
        /** NOMIS prison Id */
        prisonId: string
      }
    }
    responses: {
      /** Mapping list Returned */
      200: {
        content: {
          'application/json': components['schemas']['RoomMappingDto'][]
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Creates a new room mapping. Requires role NOMIS_VISITS */
  createRoomMapping: {
    parameters: {
      path: {
        /** NOMIS prison Id */
        prisonId: string
      }
    }
    responses: {
      /** Visit mapping entry created */
      201: unknown
      /** mapping for this nomis room and prison already exists */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VisitMappingDto']
      }
    }
  }
  /** Creates a new visit and decrements the visit balance. Requires role NOMIS_VISITS */
  createMapping: {
    responses: {
      /** Visit mapping entry created */
      201: unknown
      /** Nomis or VSIP ids already exist */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VisitMappingDto']
      }
    }
  }
  /** Deletes all rows from the the visit id table. Requires role NOMIS_VISITS */
  deleteVisitIdMappings: {
    parameters: {
      query: {
        /** if true delete mapping entries created by the migration process only (synchronisation records are unaffected) */
        onlyMigrated?: boolean
      }
    }
    responses: {
      /** Visit id mappings deleted */
      204: {
        content: {
          'application/json': { [key: string]: unknown }
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Creates a mapping between nomis Incentive ids and Incentive service id. Requires ROLE_NOMIS_INCENTIVES */
  createMapping_1: {
    responses: {
      /** Incentive mapping entry created */
      201: unknown
      /** Nomis or Incentive ids already exist */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IncentiveMappingDto']
      }
    }
  }
  /** Deletes all rows from the the incentive mapping table. Requires role NOMIS_INCENTIVES */
  deleteIncentiveMappings: {
    parameters: {
      query: {
        /** if true delete mapping entries created by the migration process only (synchronisation records are unaffected) */
        onlyMigrated?: boolean
      }
    }
    responses: {
      /** Incentive mappings deleted */
      204: {
        content: {
          'application/json': { [key: string]: unknown }
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a room mapping by NOMIS prison id and NOMIS room id. Requires role NOMIS_VISITS */
  getRoomMapping: {
    parameters: {
      path: {
        /** NOMIS prison Id */
        prisonId: string
        /** NOMIS room description */
        nomisRoomDescription: string
      }
    }
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['RoomMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** NOMIS room description does not exist in the mapping table for the given prison */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a mapping by VSIP id. Requires role NOMIS_VISITS */
  getVisitMappingGivenVsipId: {
    parameters: {
      path: {
        /** VSIP Id */
        vsipId: string
      }
    }
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['VisitMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** VSIP id does not exist in mapping table */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a mapping by NOMIS id. Requires role NOMIS_VISITS */
  getVisitMappingGivenNomisId: {
    parameters: {
      path: {
        /** NOMIS Id */
        nomisId: string
      }
    }
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['VisitMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** NOMIS id does not exist in mapping table */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieve all mappings of type 'MIGRATED' for the given migration id (identifies a single migration run). Results are paged. */
  getMigratedVisitMappingsByMigrationId: {
    parameters: {
      query: {
        pageRequest: components['schemas']['Pageable']
      }
      path: {
        /** Migration Id */
        migrationId: string
      }
    }
    responses: {
      /** Mapping page returned */
      200: {
        content: {
          'application/json': components['schemas']['VisitMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Requires role NOMIS_VISITS */
  getLatestMigratedVisitMapping: {
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['VisitMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** No mappings found at all for any migration */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a mapping by NOMIS id. Requires role ROLE_NOMIS_INCENTIVES */
  getIncentiveMappingGivenNomisId: {
    parameters: {
      path: {
        /** NOMIS booking ID */
        bookingId: string
        /** NOMIS incentive sequence */
        incentiveSequence: string
      }
    }
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['IncentiveMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** NOMIS incentive id does not exist in mapping table */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieve all mappings of type 'MIGRATED' for the given migration id (identifies a single migration run). Results are paged. */
  getMigratedVisitMappingsByMigrationId_1: {
    parameters: {
      query: {
        pageRequest: components['schemas']['Pageable']
      }
      path: {
        /** Migration Id */
        migrationId: string
      }
    }
    responses: {
      /** Mapping page returned */
      200: {
        content: {
          'application/json': components['schemas']['IncentiveMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Requires role READ_MAPPING, UPDATE_MAPPING or ADMIN_MAPPING */
  getLatestMigratedIncentiveMapping: {
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['IncentiveMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** No mappings found at all for any migration */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Retrieves a mapping by Incentive id. Requires role ROLE_NOMIS_INCENTIVES */
  getIncentiveMappingGivenIncentiveId: {
    parameters: {
      path: {
        /** Incentive Id */
        incentiveId: string
      }
    }
    responses: {
      /** Mapping Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['IncentiveMappingDto']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** VSIP id does not exist in mapping table */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Deletes the incentive mapping table. Requires role NOMIS_INCENTIVES */
  deleteIncentiveMapping: {
    parameters: {
      path: {
        /** Incentive Id */
        incentiveId: string
      }
    }
    responses: {
      /** Incentive mapping deleted */
      204: never
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Removes room mapping given the prison and nomis room description. Requires role NOMIS_VISITS */
  deleteRoomMapping: {
    parameters: {
      path: {
        /** NOMIS prison Id */
        prisonId: string
        /** NOMIS room description */
        nomisRoomDescription: string
      }
    }
    responses: {
      /** Visit room mapping deleted */
      204: never
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VisitMappingDto']
      }
    }
  }
}
