---
# Per environment values which override defaults in hmpps-nomis-sync-dashboard/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: nomis-sync-dashboard-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://nomis-sync-dashboard-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_MIGRATION_API_URL: "https://prisoner-nomis-migration-preprod.hmpps.service.justice.gov.uk"
    NOMIS_PRISONER_API_URL: "https://nomis-prisoner-api-preprod.prison.service.justice.gov.uk"
    MAPPING_API_URL: "https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk"
    ACTIVITIES_API_URL: "https://activities-api-preprod.prison.service.justice.gov.uk"
    APPINSIGHTS_COMPONENT: "nomisapi-preprod"
    ENVIRONMENT_NAME: PRE-PRODUCTION

  scheduledDowntime:
    enabled: true
    startup: '29 6 * * 1-5' # Start at 6.29am UTC Monday-Friday
    shutdown: '58 21 * * 1-5' # Stop at 9.58pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod

  elastiCacheAlertsClusterIds:
    cp-e9f6ec889153ff8c-001: "HMPPS NOMIS Sync Dashboard ElastiCache Cluster Node 1"
    cp-e9f6ec889153ff8c-002: "HMPPS NOMIS Sync Dashboard ElastiCache Cluster Node 2"
