---
# Per environment values which override defaults in hmpps-nomis-sync-dashboard/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: nomis-sync-dashboard-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://nomis-sync-dashboard-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    NOMIS_MIGRATION_API_URL: "https://prisoner-nomis-migration-dev.hmpps.service.justice.gov.uk"
    NOMIS_PRISONER_API_URL: "https://nomis-prisoner-api-dev.prison.service.justice.gov.uk"
    MAPPING_API_URL: "https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk"
    ACTIVITIES_API_URL: "https://activities-api-dev.prison.service.justice.gov.uk"
    APPINSIGHTS_COMPONENT: "nomisapi-t3"
    ENVIRONMENT_NAME: DEV

  scheduledDowntime:
    enabled: true
    startup: '29 6 * * 1-5' # Start at 6.29am UTC Monday-Friday
    shutdown: '58 19 * * 1-5' # Stop at 7.58pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod

