---
# Per environment values which override defaults in hmpps-nomis-sync-dashboard/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: nomis-sync-dashboard-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://nomis-sync-dashboard-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_MIGRATION_API_URL: "https://prisoner-nomis-migration-preprod.hmpps.service.justice.gov.uk"
    NOMIS_PRISONER_API_URL: "https://nomis-prsner-pp.aks-live-1.studio-hosting.service.justice.gov.uk"
    MAPPING_API_URL: "https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk"
    APPINSIGHTS_COMPONENT: "nomisapi-preprod"
    ENVIRONMENT_NAME: PRE-PRODUCTION

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon

