---
# Per environment values which override defaults in hmpps-nomis-sync-dashboard/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: nomis-sync-dashboard.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://nomis-sync-dashboard.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    NOMIS_MIGRATION_API_URL: "https://prisoner-nomis-migration.hmpps.service.justice.gov.uk"
    NOMIS_PRISONER_API_URL: "https://nomis-prisoner-api.prison.service.justice.gov.uk"
    MAPPING_API_URL: "https://nomis-sync-prisoner-mapping.hmpps.service.justice.gov.uk"
    ACTIVITIES_API_URL: "https://activities-api.prison.service.justice.gov.uk"
    APPINSIGHTS_COMPONENT: "nomisapi-prod"

generic-prometheus-alerts:
  alertSeverity: syscon

